# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d45c5eb896611bf39ff53d2bc92e35ae9a21d8b5cc963a0f30398ceb13bf0118d44395556a7e2070bdc81ff8c83c6a86874bd950a99feee4c97218917eb169

test:
  secret_key_base: 0c98d115e9f48d58192b53542877090beb717b8a3b0ef81fa2fb67e225597cb71349abd7945751f9a8b7716dff3a5d24fd1fe5cd46076a562c11d7412516b60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
